server:
  port: 8770
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
      - id: service-ribbon
        uri: lb://service-ribbon
        predicates:
        - Path=/ribbon/**
        filters:
        - StripPrefix=1

      - id: service-feign
        uri: lb://service-feign
        predicates:
        - Path=/feign/**
        filters:
        - StripPrefix=1
#  profiles: after_route