server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    #    Eureka Server 在运行期间会去统计心跳失败比例在 15 分钟之内是否低于 85%，
    #    如果低于 85%，Eureka Server 会将这些实例保护起来，让这些实例不会过期，
    #    但是在保护期内如果服务刚好这个服务提供者非正常下线了，此时服务消费者就会拿到一个无效的服务实例，
    #    此时会调用失败，对于这个问题需要服务消费者端要有一些容错机制，如重试，断路器等。
    renewal-percent-threshold: 0.49 #本地测试如果eureka出现连接错误，可以调低参数，默认0.85
#   是否开启自我保护模式
    enable-self-preservation: true
  client:
#    自己是否当做服务注册
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/